### ISSUE TITLE
Micropython 1.15 support and Pico board?

### ISSUE THREAD

**Issue by pavl0squiet0s** [fizista/micropython-mcron#2]
Are there any plans to support 1.15 ver of micropython? 

I've tried every installation options, but still failed to install the "u"mcron package to Pico board

**Comment by fizista** [comment]
In theory, this library should work.

On micropython version 1.13 it works.

And what errors are there?

**Comment by pavl0squiet0s** [comment]
My setup: Windows 10, Thonny setup to micropython and running custom UF2 pimoroni image based on upython 1.15 (due to LED matrix hat I'm using from pimoroni: pico-unicorn).

1. upip is installed in the "Tools -> manage packages". Got the following error while installing mcron from "Tools -> manage packages" (from PyPi):

Installing to temp directory
Error installing 'micropython-mcron': b'403'
Installing to: D:\TEMPFI~1\Temp\tmp3xixyhq1\

micropip returned with error code 1

2. Cloned git, tried to manually install from local file (Tools -> Plugins). No luck - same error.
3. Manually moved 3 files into Pico and run a test program. 

Traceback (most recent call last):
  File "<stdin>", line 16, in <module>
  File "mcron/__init__.py", line 192, in init_timer
ValueError: Timer doesn't exist

Do I need to run a script since I've manually moved the files? If yes then how? In not, why did the installation failed in point 1?

**Comment by fizista** [comment]
> My setup: Windows 10, Thonny setup to micropython and running custom UF2 pimoroni image based on upython 1.15 (due to LED matrix hat I'm using from pimoroni: pico-unicorn).
> 
> 1. upip is installed in the "Tools -> manage packages". Got the following error while installing mcron from "Tools -> manage packages" (from PyPi):
> 
> Installing to temp directory
> Error installing 'micropython-mcron': b'403'
> Installing to: D:\TEMPFI~1\Temp\tmp3xixyhq1\
> 
> micropip returned with error code 1

This looks like a problem with the Thonny editor.

The 403 code reminds me of an error code in the HTTP protocol. Perhaps it is related to the problem.

> 
> 1. Cloned git, tried to manually install from local file (Tools -> Plugins). No luck - same error.
> 2. Manually moved 3 files into Pico and run a test program.

Probably the same problem as above.

Sure enough, the official package installation methods work, including manually copying files.

See here:
https://github.com/fizista/micropython-mcron#install

> 
> Traceback (most recent call last):
> File "", line 16, in
> File "mcron/**init**.py", line 192, in init_timer
> ValueError: Timer doesn't exist

I can only assume that the UF2 pimoroni image, does not support the Timer class from the machine module.  I have no way to check this.

> 
> Do I need to run a script since I've manually moved the files? If yes then how? In not, why did the installation failed in point 1?

**Comment by pavl0squiet0s** [comment]
Thank you, I'll mark it as closed as it does not seam it's anything to do with mcron package.

**Comment by mhajder** [comment]
Hi,
In case anyone else encounters this problem, I found a solution:

Just change:
https://github.com/fizista/micropython-mcron/blob/3e2b4359984c0ba8102fd0b4ea49ea9b2e9b0c55/mcron/__init__.py#L200
To:
```python
timer = machine.Timer()
```
**Tested on:**
Board: Pico W
MicroPython version: [v1.19.1-779-g57bb1e047 (2022-12-19) .uf2](https://micropython.org/resources/firmware/rp2-pico-w-20221219-unstable-v1.19.1-779-g57bb1e047.uf2)

Maybe someone will get here from the search engine, so I wanted to post this information.
